name: bpref
channels:
  - defaults
dependencies:
  - python=3.6
  - pytorch=1.4.0
  - cudatoolkit=10.1
  - absl-py
  - pyparsing
  - pip
  - pip:
    - termcolor
    - tb-nightly
    - imageio
    - imageio-ffmpeg
    - matplotlib
    - glfw==1.11.2
    - scikit-image
